"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { addOperation } from "../components/PortalShell";

export default function LoginPage() {
  const router=useRouter(); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [error,setError]=useState(""); const [show,setShow]=useState(false);
  useEffect(()=>{if(sessionStorage.getItem("seller-demo-expired")==="true"){setError("登录已过期，请重新输入账号和密码");sessionStorage.removeItem("seller-demo-expired");}},[]);
  const login=(e:React.FormEvent)=>{e.preventDefault();if(email!=="seller@example.com"||password!=="demo123"){setError("账号或密码不正确，请使用页面中的演示账号");return;}localStorage.setItem("seller-demo-auth","true");localStorage.setItem("seller-demo-auth-expires",String(Date.now()+60_000));addOperation("登录平台","账户","通过本地演示登录页进入系统，会话有效期 1 分钟");router.push("/");};
  return <main className="login-page"><section className="login-brand-panel"><div className="login-brand"><div className="brand-mark">sp</div><div><strong>sellpilot</strong><span>SELLER CENTRAL</span></div></div><div className="login-copy"><p>本地卖家运营中心</p><h1>让每一次店铺操作<br/>清晰、可靠、可追踪。</h1><ul><li><i>✓</i>管理商品价格与库存</li><li><i>✓</i>处理退款订单</li><li><i>✓</i>下载经营报表</li><li><i>✓</i>审计全部操作记录</li></ul></div><small>LOCAL DEMO · 不连接真实卖家账户</small></section><section className="login-form-panel"><form onSubmit={login}><div className="mobile-login-brand"><div className="brand-mark">sp</div><strong>sellpilot</strong></div><p className="eyebrow">SELLER CENTRAL · US</p><h2>登录卖家平台</h2><p className="login-subtitle">使用演示账号继续访问本地管理后台</p><div className="demo-account"><span>演示账号</span><code>seller@example.com</code><code>demo123</code></div>{error&&<div className="login-error">! {error}</div>}<label>登录邮箱<input data-testid="login-email" value={email} onChange={(e)=>setEmail(e.target.value)} autoComplete="username" placeholder="请输入登录邮箱" /></label><label>登录密码<div className="password-field"><input data-testid="login-password" type={show?"text":"password"} value={password} onChange={(e)=>setPassword(e.target.value)} autoComplete="current-password" placeholder="请输入登录密码"/><button type="button" onClick={()=>setShow(!show)}>{show?"隐藏":"显示"}</button></div></label><div className="login-options"><span>会话有效期：1 分钟</span><button type="button">忘记密码？</button></div><button data-testid="login-submit" className="login-submit">登录</button><small className="login-note">这是本地 RPA 演示环境，请勿输入真实凭据。</small></form></section></main>;
}
