"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import PortalShell, { addOperation } from "./PortalShell";

const seedProducts = [
  { sku: "WBH-2026-BLK", asin: "B0D8K2L7P1", name: "无线蓝牙降噪耳机", price: 79.99, stock: 86, listed: true },
  { sku: "CGM-042-SLV", asin: "B0C9R5M2Q8", name: "便携式咖啡研磨机", price: 46.5, stock: 12, listed: true },
  { sku: "LST-110-GRY", asin: "B0B7N4H6T3", name: "人体工学笔记本支架", price: 38.9, stock: 4, listed: true },
  { sku: "HUB-7IN1-GRY", asin: "B0F1S8J4W6", name: "USB-C 7合1扩展坞", price: 55, stock: 0, listed: false },
];

const refunds = [
  { id: "RMA-20260715-0048", order: "114-7829351-6845012", buyer: "Lin Chen", product: "无线蓝牙降噪耳机", amount: "US$ 79.99", reason: "商品与描述不符", status: "待处理", created: "2026-07-15 13:42", note: "买家反馈耳机右侧偶有杂音，申请退货退款。" },
  { id: "RMA-20260714-0039", order: "113-5912048-3287461", buyer: "Emma Wilson", product: "便携式咖啡研磨机", amount: "US$ 46.50", reason: "不再需要", status: "已批准", created: "2026-07-14 16:08", note: "商品未拆封，已提供退货标签。" },
  { id: "RMA-20260713-0027", order: "112-4083765-9982140", buyer: "Noah Smith", product: "人体工学笔记本支架", amount: "US$ 38.90", reason: "尺寸不合适", status: "退款完成", created: "2026-07-13 10:25", note: "退货商品已入库，退款原路退回。" },
];

export function DashboardPage() {
  return <PortalShell title="首页" subtitle="查看店铺概况并快速进入日常业务操作"><div className="home-kpis"><Kpi label="在售商品" value="127" note="3 件库存不足" /><Kpi label="待处理退款" value="1" note="需在 24 小时内处理" /><Kpi label="本月销售额" value="US$ 42,680" note="较上月 ↑ 12.5%" /><Kpi label="今日操作" value="18" note="全部执行成功" /></div><div className="portal-home-grid"><section className="panel quick-entry"><div className="panel-head"><div><h2>快捷入口</h2><p>常用卖家操作</p></div></div><div className="quick-grid"><Link href="/products"><span>▦</span><strong>查询商品</strong><small>改价、改库存、上下架</small></Link><Link href="/refunds"><span>↩</span><strong>退款订单</strong><small>查询并查看退款详情</small></Link><Link href="/reports"><span>⌁</span><strong>下载报表</strong><small>销售、商品与退款报表</small></Link><Link href="/logs"><span>≡</span><strong>操作日志</strong><small>追踪后台操作记录</small></Link></div></section><section className="panel pending-list"><div className="panel-head"><div><h2>待处理事项</h2><p>建议优先完成</p></div></div><Link href="/products"><b className="warn-dot">!</b><div><strong>3 件商品库存偏低</strong><small>预计 5 天内售罄</small></div><em>去处理 ›</em></Link><Link href="/refunds"><b className="red-dot">1</b><div><strong>1 个退款申请待审核</strong><small>最晚今日 18:00 前处理</small></div><em>去处理 ›</em></Link><Link href="/reports"><b className="blue-dot">⌁</b><div><strong>月度销售报告可下载</strong><small>已包含截至昨日的数据</small></div><em>去下载 ›</em></Link></section></div><section className="panel activity-panel"><div className="panel-head"><div><h2>今日店铺表现</h2><p>2026年7月15日</p></div></div><div className="simple-chart"><div><span style={{height:"45%"}} /><small>09:00</small></div><div><span style={{height:"62%"}} /><small>11:00</small></div><div><span style={{height:"52%"}} /><small>13:00</small></div><div><span style={{height:"84%"}} /><small>15:00</small></div><div><span style={{height:"72%"}} /><small>17:00</small></div><div><span style={{height:"92%"}} /><small>19:00</small></div></div></section></PortalShell>;
}

export function ProductsPage() {
  const [items, setItems] = useState(seedProducts); const [query, setQuery] = useState(""); const [status, setStatus] = useState("全部"); const [message, setMessage] = useState(""); const [dirty, setDirty] = useState<Record<string, boolean>>({}); const [saved, setSaved] = useState<Record<string, boolean>>({});
  useEffect(() => { const stored = localStorage.getItem("seller-demo-products"); if (stored) { try { setItems(JSON.parse(stored)); } catch { localStorage.removeItem("seller-demo-products"); } } }, []);
  const shown = items.filter((p) => `${p.sku} ${p.asin} ${p.name}`.toLowerCase().includes(query.toLowerCase()) && (status === "全部" || (status === "已上架" ? p.listed : !p.listed)));
  const update = (sku: string, field: "price" | "stock", value: number) => { setItems((old) => old.map((p) => p.sku === sku ? { ...p, [field]: value } : p)); setDirty((old) => ({ ...old, [sku]: true })); setSaved((old) => ({ ...old, [sku]: false })); };
  const save = (p: typeof seedProducts[number]) => { localStorage.setItem("seller-demo-products", JSON.stringify(items)); addOperation("修改商品", p.sku, `价格 US$ ${p.price.toFixed(2)}，库存 ${p.stock}`); setDirty((old) => ({ ...old, [p.sku]: false })); setSaved((old) => ({ ...old, [p.sku]: true })); setMessage(`${p.sku} 的修改已保存，刷新页面后仍会保留`); window.setTimeout(() => setMessage(""), 2600); };
  const toggle = (sku: string) => { setItems((old) => { const next = old.map((p) => { if (p.sku !== sku) return p; addOperation(p.listed ? "下架商品" : "上架商品", sku, p.name); return { ...p, listed: !p.listed }; }); localStorage.setItem("seller-demo-products", JSON.stringify(next)); return next; }); setSaved((old) => ({ ...old, [sku]: true })); };
  return <PortalShell title="商品管理" subtitle="查询商品并修改价格、库存及销售状态"><section className="panel product-panel"><div className="product-toolbar"><label><span>⌕</span><input data-testid="product-search" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="输入商品名称、SKU 或 ASIN" /></label><select data-testid="product-status" value={status} onChange={(e) => setStatus(e.target.value)}><option>全部</option><option>已上架</option><option>已下架</option></select><button className="primary-button" onClick={() => setMessage(`查询到 ${shown.length} 件商品`)}>查询商品</button></div>{message && <div className="inline-success">✓ {message}</div>}<div className="table-wrap"><table className="product-table"><colgroup><col className="col-product"/><col className="col-sku"/><col className="col-price"/><col className="col-stock"/><col className="col-status"/><col className="col-actions"/></colgroup><thead><tr><th>商品信息</th><th>SKU / ASIN</th><th>价格（US$）</th><th>可售库存</th><th>销售状态</th><th>操作</th></tr></thead><tbody>{shown.map((p, i) => <tr key={p.sku} className={dirty[p.sku] ? "product-row-dirty" : ""}><td><div className="product-info-cell"><div className={`product-thumb p${i+1}`}>{["🎧","☕","▱","⌘"][i]}</div><span><strong>{p.name}</strong><small>{p.listed ? "可在前台购买" : "当前不对买家展示"}</small></span></div></td><td><code>{p.sku}</code><small>{p.asin}</small></td><td><input data-testid={`price-${p.sku}`} className="cell-input price-input" type="number" min="0" step="0.01" value={p.price} onChange={(e) => update(p.sku, "price", Number(e.target.value))} /></td><td><input data-testid={`stock-${p.sku}`} className="cell-input stock-input" type="number" min="0" value={p.stock} onChange={(e) => update(p.sku, "stock", Number(e.target.value))} /><small className={p.stock < 10 ? "stock-warn" : ""}>{p.stock < 10 ? "库存预警" : "库存正常"}</small></td><td><span className={`listing ${p.listed ? "online" : "offline"}`}><i />{p.listed ? "已上架" : "已下架"}</span></td><td><div className="product-actions"><div className="row-buttons"><button data-testid={`save-${p.sku}`} className={dirty[p.sku] ? "save-pending" : ""} disabled={!dirty[p.sku]} onClick={() => save(p)}>{dirty[p.sku] ? "保存修改" : "已保存"}</button><button data-testid={`toggle-${p.sku}`} className={p.listed ? "danger" : "publish"} onClick={() => toggle(p.sku)}>{p.listed ? "下架" : "上架"}</button></div><small className={dirty[p.sku] ? "save-state pending" : "save-state"}>{dirty[p.sku] ? "● 有未保存修改" : saved[p.sku] ? "✓ 刚刚已保存" : "✓ 数据已保存"}</small></div></td></tr>)}</tbody></table></div></section></PortalShell>;
}

export function RefundsPage() {
  const [query, setQuery] = useState(""); const [status, setStatus] = useState("全部状态"); const [selected, setSelected] = useState<typeof refunds[number] | null>(null);
  const shown = refunds.filter((r) => `${r.id} ${r.order} ${r.buyer} ${r.product}`.toLowerCase().includes(query.toLowerCase())).filter((r) => status === "全部状态" || r.status === status);
  return <PortalShell title="退款订单" subtitle="查询退款申请并查看完整处理信息"><section className="panel refund-panel"><div className="product-toolbar"><label><span>⌕</span><input data-testid="refund-search" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="退款单号、订单号、买家或商品" /></label><select value={status} onChange={(e) => setStatus(e.target.value)}><option>全部状态</option><option>待处理</option><option>已批准</option><option>退款完成</option></select><button className="primary-button">查询退款单</button></div><div className="table-wrap"><table><thead><tr><th>退款单号</th><th>关联订单</th><th>商品 / 买家</th><th>退款金额</th><th>原因</th><th>状态</th><th>操作</th></tr></thead><tbody>{shown.map((r) => <tr key={r.id}><td><strong>{r.id}</strong><small>{r.created}</small></td><td><code>{r.order}</code></td><td><strong>{r.product}</strong><small>{r.buyer}</small></td><td><strong>{r.amount}</strong></td><td>{r.reason}</td><td><span className={`status ${r.status === "待处理" ? "warning" : r.status === "已批准" ? "info" : "success"}`}><i />{r.status}</span></td><td><button data-testid={`refund-detail-${r.id}`} className="table-button" onClick={() => { setSelected(r); addOperation("查看退款详情", r.id, `关联订单 ${r.order}`); }}>查看详情</button></td></tr>)}</tbody></table></div></section>{selected && <div className="modal-backdrop" role="presentation" onClick={() => setSelected(null)}><article className="detail-modal" role="dialog" aria-modal="true" onClick={(e) => e.stopPropagation()}><header><div><p>退款详情</p><h2>{selected.id}</h2></div><button aria-label="关闭" onClick={() => setSelected(null)}>×</button></header><div className="detail-status"><span className={`status ${selected.status === "待处理" ? "warning" : "success"}`}><i />{selected.status}</span><small>申请时间：{selected.created}</small></div><dl><div><dt>关联订单</dt><dd>{selected.order}</dd></div><div><dt>买家</dt><dd>{selected.buyer}</dd></div><div><dt>商品</dt><dd>{selected.product}</dd></div><div><dt>退款金额</dt><dd>{selected.amount}</dd></div><div><dt>退款原因</dt><dd>{selected.reason}</dd></div><div className="full"><dt>买家说明</dt><dd>{selected.note}</dd></div></dl><footer>{selected.status === "待处理" && <><button className="outline-button" onClick={() => setSelected(null)}>暂不处理</button><button className="primary-button" onClick={() => { addOperation("批准退款", selected.id, selected.amount); setSelected(null); }}>批准退款</button></>}</footer></article></div>}</PortalShell>;
}

export function ReportsPage() {
  const [type, setType] = useState("销售报表"); const [range, setRange] = useState("本月"); const [message, setMessage] = useState("");
  const reports = [{name:"销售报表",desc:"销售额、订单量、平均客单价",size:"18 KB"},{name:"商品报表",desc:"商品价格、库存和销售状态",size:"12 KB"},{name:"退款报表",desc:"退款原因、金额和处理状态",size:"9 KB"}];
  const download = (name = type) => { const csv = "\ufeff报表类型,时间范围,生成时间\n" + `${name},${range},2026-07-15 14:35`; const url = URL.createObjectURL(new Blob([csv], {type:"text/csv"})); const a=document.createElement("a");a.href=url;a.download=`${name}-${range}.csv`;a.click();URL.revokeObjectURL(url);addOperation("下载报表",name,range);setMessage(`${name}已下载`); };
  return <PortalShell title="报表中心" subtitle="生成并下载店铺经营数据报表"><section className="report-download-grid"><article className="panel report-config"><div className="panel-head"><div><h2>生成报表</h2><p>选择类型和统计周期</p></div></div><div className="form-stack"><label>报表类型<select data-testid="report-type" value={type} onChange={(e)=>setType(e.target.value)}>{reports.map((r)=><option key={r.name}>{r.name}</option>)}</select></label><label>统计周期<select value={range} onChange={(e)=>setRange(e.target.value)}><option>今天</option><option>过去 7 天</option><option>本月</option><option>上月</option></select></label><button data-testid="download-report" className="primary-button" onClick={()=>download()}>↓ 下载报表</button>{message&&<div className="inline-success">✓ {message}</div>}</div></article><article className="panel available-reports"><div className="panel-head"><div><h2>可下载报表</h2><p>CSV 格式，可使用 Excel 打开</p></div></div>{reports.map((r)=><div key={r.name}><span>▤</span><div><strong>{r.name}</strong><small>{r.desc} · {r.size}</small></div><button onClick={()=>download(r.name)}>下载</button></div>)}</article></section><section className="panel report-history"><div className="panel-head"><div><h2>最近下载记录</h2><p>近 30 天生成的报表</p></div></div><table><thead><tr><th>报表名称</th><th>统计周期</th><th>生成时间</th><th>操作人</th><th>状态</th></tr></thead><tbody><tr><td><strong>销售报表</strong></td><td>2026年6月</td><td>2026-07-01 09:12</td><td>seller@example.com</td><td><span className="status success"><i/>已生成</span></td></tr></tbody></table></section></PortalShell>;
}

export function LogsPage() {
  const seeded = [{id:1,time:"2026/7/15 14:18:32",user:"seller@example.com",action:"修改库存",target:"LST-110-GRY",detail:"库存从 3 修改为 4",result:"成功"},{id:2,time:"2026/7/15 13:52:06",user:"seller@example.com",action:"下架商品",target:"HUB-7IN1-GRY",detail:"商品暂时停止销售",result:"成功"},{id:3,time:"2026/7/15 11:24:48",user:"seller@example.com",action:"下载报表",target:"销售报表",detail:"统计周期：本月",result:"成功"}];
  const [query,setQuery]=useState(""); const [action,setAction]=useState("全部操作"); const local=typeof window!=="undefined"?JSON.parse(localStorage.getItem("seller-demo-logs")||"[]"):[]; const all=[...local,...seeded];
  const shown=useMemo(()=>all.filter((l:any)=>(action==="全部操作"||l.action===action)&&`${l.action} ${l.target} ${l.detail}`.toLowerCase().includes(query.toLowerCase())),[all,action,query]);
  return <PortalShell title="操作日志" subtitle="查看登录、商品、退款及报表操作记录"><section className="panel logs-panel"><div className="product-toolbar"><label><span>⌕</span><input data-testid="log-search" value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="搜索操作内容或对象" /></label><select value={action} onChange={(e)=>setAction(e.target.value)}><option>全部操作</option><option>修改商品</option><option>上架商品</option><option>下架商品</option><option>查看退款详情</option><option>批准退款</option><option>下载报表</option><option>退出登录</option></select><button className="primary-button">查询日志</button></div><div className="log-count">共 {shown.length} 条操作记录</div><div className="table-wrap"><table><thead><tr><th>操作时间</th><th>操作人</th><th>操作类型</th><th>操作对象</th><th>详细信息</th><th>结果</th></tr></thead><tbody>{shown.map((l:any)=><tr key={l.id}><td>{l.time}</td><td>{l.user}</td><td><strong>{l.action}</strong></td><td><code>{l.target}</code></td><td>{l.detail}</td><td><span className="status success"><i/>{l.result}</span></td></tr>)}</tbody></table></div></section></PortalShell>;
}

function Kpi({label,value,note}:{label:string;value:string;note:string}){return <article><span>{label}</span><strong>{value}</strong><small>{note}</small></article>}
